### ISSUE TITLE
update developer docs - include demo config, include any linux updates

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#168]

**Comment by wfernandes** [comment]
@ggebel @barinek One of the major hurdles I had setting up my environment on my linux box was installing postgres.
However, after looking into this some more, I realized that since there are so many distributions of linux, instead of defining troubleshooting/faq for each distribution, we can leave it up to the users to install postgres how they see fit.

It may not be the right thing to provide installation instructions for a dependency tool. That would be like giving folks instructions on how to install docker or golang.

I suggest deleting this story but happy to discuss more.

**Comment by ggebel** [comment]
Ok @wfernandes, let's discuss on tomorrow's call

**Comment by wfernandes** [comment]
https://github.com/hexa-org/policy-orchestrator/pull/203
