### ISSUE TITLE
Spike on terraform integration

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#182]

**Comment by independentid** [comment]
Terraform integration is intended to provide support for IDQL Policy inside of [Terriform/Hashicorp configuration language](https://www.terraform.io/language/syntax/configuration).  

Terraform provides a platform to manage deployment of infrastructure in a CI/CD system.  Terraform provides support for multiple cloud providers through the use of "plugins" which enable mapping HCL to each platform's proprietary API.  Terraform then tracks state of deployed systems to ensure compliance with the defined configuration.  

In order to normalize different platform identity policy languages, a set of Hexa providers are being explored for Terraform that allow administrators to configure identity policy directly in IDQL or to reference and external IDQL policy system (e.g. such as Hexa Orchestrator, GIT, etc).

Providers under consideration:
* Hexa Provider - Common IDQL syntax and IDQL policy parsing and retrieval
* Hexa Google Provider - A provider with data mappings and resources that map IDQL policy into Google Bind policy and configuration settings.
* Hexa AWS Provider - A provider that extends IDQL support to the AWS and Cognito platform 
* Hexa Azure Provider - A provider that extends IDQL support to the Azure platform
* Others TBD

Note:  These projects are envisioned as separate providers in Terraform to avoid over-bundling of platform specific libraries. For example, if an administrator is not using Google, then we want to avoid loading Google client libraries.
