### ISSUE TITLE
secure opa call to democonfig bundle

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#195]
When deployed locally, the OPA server gets its bundle config from another local service.

When deployed in the cloud, this story will implement a secure call to the bundle server

**Comment by wfernandes** [comment]
As part of this story, we'll simply configure the bundle server to run on https instead of http.

This means that we'll need to configure the clients with a CA cert or client certs so that we can verify the handshake. This would mean  that we would need to provide the certs as part of the integration config for the OPA bundle server.

That is,

```json
{
  "bundle_url": "https://bundle-server",
  "ca_cert": "<json encoded cert here>"
}
```

**Comment by wfernandes** [comment]
We discussed further implementations of securing the opa bundle and that is being adding a simple credential mechanism to authenticate the request from OPA.
