### ISSUE TITLE
Auto generate software bill of materials (SBOM)

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#210]
From NTIA’s SBOM FAQ  “A Software Bill of Materials (SBOM) is a complete, formally structured list of components, libraries, and modules that are required to build (i.e. compile and link) a given piece of software and the supply chain relationships between them. These components can be open source or proprietary, free or paid, and widely available or restricted access.”

https://www.linuxfoundation.org/blog/what-is-an-sbom/

**Comment by barinek** [comment]
here is a link to an example - https://github.com/opensbom-generator/spdx-sbom-generator

**Comment by wfernandes** [comment]
Since the CNCF requested the SBOM to be released as a release artifact I decided to look for tools that were associated with the CNCF.

From [this blog post](https://www.cncf.io/blog/2022/02/22/security-the-value-of-sboms/) I came across [this tool called Syft](https://github.com/anchore/syft) which definitely seems to be more actively maintained.

There's also [this post from Chainguard](https://blog.chainguard.dev/what-an-sbom-can-do-for-you/) which conveniently links to a [k8s project](https://github.com/kubernetes-sigs/bom) that also generates BOM.

I'll compare the output of the three tools and see which one can be easily integrated into our pipeline.

**Comment by wfernandes** [comment]
Deciding to use Syft since it is well maintained, used by CNCF projects and also has github action that can be used as part of the github workflows.
