### ISSUE TITLE
remove application when delete from corresponding integration

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#238]

**Comment by wfernandes** [comment]
@ggebel I created a test app in the azure account called `warren-test-app2` and if you use the azure integration key, the application should show up in our Applications page.

Acceptance Steps:

1. Go ahead and delete the app from azure.
2. Wait for about a minute and the refresh the Applications page and you should see that the app is removed from the page.

**Comment by ggebel** [comment]
@wfernandes I see the app in my list, but I don't have permissions to delete it. Can you do that in the morning and let me know, then I'll refresh the Applications page



![Image](https://user-images.githubusercontent.com/83663628/195468828-71899653-4cb6-48e3-9a57-549f59f22cf1.png)

**Comment by ggebel** [comment]
It's also interesting that my terminal log shows some other entries:



![Image](https://user-images.githubusercontent.com/83663628/195471269-37f44944-210d-4ddd-b5ff-7124d942b098.png)

**Comment by wfernandes** [comment]
@ggebel Apparently my `warren-test-app` was still around but it wasn't showing up on the Applications page. I had to surprisingly use the top "Search resources" bar to find the app.

Also, I'm sure you already know this but just to confirm, the reason why `warren-test-app` wasn't showing up in the applications page is because that app didn't have a `Homepage URL`. Apparently, the Admin app filters out the applications without a `Homepage URL`.

**Comment by ggebel** [comment]
Thanks @wfernandes , I didn't know why the app did not show up on my screen. So, to clarify, the orchestrator finds `warren-test-app` but does not display it in the Application page. Does that entry get stored in my local database, or is it just an info message that shows up in the log?
