### ISSUE TITLE
Hawk authorization failing with Postman

### ISSUE THREAD

**Issue by renatosc** [hexa-org/policy-orchestrator#261]
I have the demo running fine in the browser. I am trying to communicate directly with the orchestrator APIs using Postman.

I setup the Hawk Authorization method, but I always get a **401 Unauthorized response**.  The log shows "HAWK authentication failed: Bad MAC", but I already double checked the key.

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/6549539/203191973-0d1bb865-aecf-4174-ac33-7fb923ba9dbc.png">

**Comment by MrOrangeAndHam** [comment]
Hey @renatosc. Thanks for the adding the issue. I am creating a story in our backlog to look into this.

**Comment by MrOrangeAndHam** [comment]
@renatosc To fix the issue you are running into you will need to remove the `ORCHESTRATOR_HOSTPORT: hexa-orchestrator:8885` environment variable from the docker-compose file. If that environment variable is present it is using that as part of the code when decoding the key.

When sending the request from postman you are just sending a key and not generating a key with the HOSTPORT  value present so the MAC will not match.

By removing that environment variable from the orchestrator you will be able to send requests from postman with just using the key.

This will cause problems if you are running the admin app to do things with the orchestrator since the admin app uses the orchestrator host and port when sending requests so the key would need to be added back at this time.

I hope this helps! Thank you adding the issue.
