### ISSUE TITLE
Fix authorization in demo app, tries to authenticate query params

### ISSUE THREAD

**Issue by identitynerd** [hexa-org/policy-orchestrator#94]
the below breaks
https:// cognito.aDemoUrl .com/?code=someCode

**Comment by independentid** [comment]
To confirm the error, are you just adding an arbitrary parameter to the end of a URL?  E.g.
Instead of http://localhost:8886/sales :  Succeeds
The URL http://localhost:8886/sales?param=test :  (which does fail)

**Comment by independentid** [comment]
Looking at the scenario, the issue is the rego code is doing strict path matching (which includes everything past the domain).  We need to enhance rego to support regex matching in path specifications.  Not only does /sales?a=b fail, but so will /sales<anything>

It would be useful in IDQL to specify (e.g. w/regex) that /Sales* is allowed or /Sales*?c=US is also allowed.

We could chop off parameters from the path for evaluation but then that would prevent policy on parameters.

**Comment by independentid** [comment]
In opa_support.go, the path that gets sent to opa is the original(which is correct).

To fix, we would have to change opa_support.go code from:

`input := OpaQuery{map[string]interface{}{
			"method":     "GET",
			"path":       r.RequestURI,
			"principals": []interface{}{"allusers", "allauthenticatedusers", "sales@hexaindustries.io"},
		}}`
To:
`input := OpaQuery{map[string]interface{}{
			"method":     "GET",
			"path":       strings.Split(r.RequestURI, "?")[0],
			"principals": []interface{}{"allusers", "allauthenticatedusers", "sales@hexaindustries.io"},
		}}`
		
I think the issue with this approach is that this would be a demo specific solution that impacts other apps (that may use opa_support.go).  I think enhancement to support resource path wildcards and regex per the IDQL spec is the best.  

Technically the demo app is working correctly as the policy is exact match on the URL.  In the current IDQL we do not make special provisions for parameters. In the current policy you would do this with a RegEx espression (not yet supported).

**Comment by hunarjain09** [comment]
@barinek I can work on this issue :)
